### ISSUE TITLE
Lost all Ergo

### ISSUE THREAD

**Issue by Eltoro8** [ergoplatform/ergo-wallet-android#44] opened 2021-09-22 12:59 UTC
All my Ergo was withdrawn from my account using this wallet

**Comment by MrStahlfelge** [comment] 2021-09-22 13:07
It seems that the backend has hickups at the moment so the amount shown went to 0 for you which is wrong. If the ERG are really withdawn, there would be a transaction withdrawing the ERG. Is there such a transaction?

**Comment by Eltoro8** [comment] 2021-09-22 13:14
Thank you for the quick really,
I can't see any transactions and just goes to a scene fetching data, will
the issue be fixed and go back to normal?

Cheers,
Ben

**Comment by MrStahlfelge** [comment] 2021-09-22 13:17
As soon as ergo explorer is back online the correct balance will be shown again

**Comment by Eltoro8** [comment] 2021-09-22 13:20
Thank you,

Had me very worried! Hope it's back up soon

Cheers

**Comment by MrStahlfelge** [comment] 2021-09-22 13:49
It is back up, when the problem is solved for you please close the issue

**Closed** 2021-09-22 15:34 UTC
